app = "pennystockadvisor"
primary_region = "ewr"

[build]
  image = "python:3.11-slim"

[env]
  FINNHUB_API_KEY = "c9f3ed5237d3cc88d8ea36d5e1a0c8ce"

[services]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
